import test,{before,after}from'node:test';import assert from'node:assert/strict';
import {createApp,leaderboard,weekStart}from'../server/main.js';import {loadConfig,gameConfig,competitionKey}from'../server/config.js';import{Store}from'../server/db.js';
let app,base;
before(async()=>{const config={...loadConfig({PORT:'0',HOST:'127.0.0.1'}),disableScheduler:true,maxActiveMatches:64};app=await createApp({config,store:new Store(':memory:')});base=await app.listen();});
after(async()=>await app.close());
async function client(){const r=await fetch(base+'/api/me'),cookie=r.headers.get('set-cookie').split(';')[0],me=await r.json();return{cookie,me,async req(path,body,extra={}){const response=await fetch(base+path,{method:body?'POST':'GET',headers:{cookie,origin:base,'content-type':'application/json','x-csrf-token':me.csrfToken,...extra},body:body?JSON.stringify(body):undefined});let data;try{data=await response.json();}catch{data=null;}return{status:response.status,data};}};}
const options=()=>({requestId:crypto.randomUUID(),boardPreset:'beginner',aiDifficulty:'normal',mode:'practice',context:'world'});
async function started(c){const {data:s}=await c.req('/api/matches',options());const r=await c.req(`/api/matches/${s.id}/actions`,{requestId:crypto.randomUUID(),action:{type:'start',cell:40}});assert.equal(r.status,200);return r.data.snapshot;}
test('health endpoint returns success',async()=>assert.equal((await fetch(base+'/api/health')).status,200));
test('static root and CSP are served without framework code',async()=>{const r=await fetch(base);assert.equal(r.status,200);assert.ok(r.headers.get('content-security-policy').includes("frame-ancestors 'none'"));assert.ok((await r.text()).includes('humanBoard'));});
test('server files and environment files are not served',async()=>{for(const path of['/.env','/server/schema.sql','/server/main.js','/data/minesweeper.sqlite'])assert.equal((await fetch(base+path)).status,404);});
test('guest match creation succeeds and cannot be ranked',async()=>{const c=await client(),r=await c.req('/api/matches',{...options(),mode:'ranked'});assert.equal(r.status,201);assert.equal(r.data.eligibility.eligible,false);assert.ok(r.data.eligibility.reasons.includes('guest'));});
test('browser-supplied guild and score fields are rejected',async()=>{const c=await client();for(const extra of[{guild_id:'fake'},{score:999999}])assert.equal((await c.req('/api/matches',{...options(),...extra})).status,422);});
test('match creation requires CSRF token',async()=>{const c=await client();assert.equal((await c.req('/api/matches',options(),{'x-csrf-token':'wrong'})).status,403);});
test('match creation requires same origin',async()=>{const c=await client();assert.equal((await c.req('/api/matches',options(),{origin:'https://attacker.invalid'})).status,403);});
test('duplicate creation id returns original match',async()=>{const c=await client(),body=options(),a=await c.req('/api/matches',body),b=await c.req('/api/matches',body);assert.equal(a.data.id,b.data.id);});
test('creation id cannot be reused with a different body',async()=>{const c=await client(),body=options();await c.req('/api/matches',body);assert.equal((await c.req('/api/matches',{...body,aiDifficulty:'hard'})).status,409);});
test('one owner cannot keep multiple active matches',async()=>{const c=await client();await c.req('/api/matches',options());assert.equal((await c.req('/api/matches',options())).status,409);});
test('different owner cannot read or act on a match',async()=>{const a=await client(),b=await client(),s=await started(a);assert.equal((await b.req(`/api/matches/${s.id}`)).status,404);assert.equal((await b.req(`/api/matches/${s.id}/actions`,{requestId:crypto.randomUUID(),action:{type:'resign'}})).status,404);});
test('unknown UUID error does not crash audit logging',async()=>{const c=await client();assert.equal((await c.req(`/api/matches/${crypto.randomUUID()}/actions`,{requestId:crypto.randomUUID(),action:{type:'resign'}})).status,404);assert.equal((await fetch(base+'/api/health')).status,200);});
test('active snapshots expose no hidden layout or seed',async()=>{const c=await client(),s=await started(c);assert.equal(s.seeds,undefined);assert.equal(s.boards.human.mines,undefined);assert.equal(s.boards.jev.adjacent,undefined);assert.equal(s.boards.human.cells.length,81);});
test('active replay and postgame analytics endpoints are locked',async()=>{const c=await client(),s=await started(c);for(const suffix of['replay','analytics','export?format=jsonl'])assert.equal((await c.req(`/api/matches/${s.id}/${suffix}`)).status,409);});
test('wrong human board revision is rejected',async()=>{const c=await client(),s=await started(c),cell=s.boards.human.cells.indexOf(-1);const r=await c.req(`/api/matches/${s.id}/actions`,{requestId:crypto.randomUUID(),expectedBoardRevision:0,action:{type:'setFlag',cell,value:true}});assert.equal(r.status,409);assert.equal(r.data.error.code,'stale_board_revision');});
test('idempotent action is applied exactly once',async()=>{const c=await client(),s=await started(c),cell=s.boards.human.cells.indexOf(-1);const body={requestId:crypto.randomUUID(),expectedBoardRevision:s.boards.human.revision,action:{type:'setFlag',cell,value:true}};const a=await c.req(`/api/matches/${s.id}/actions`,body),b=await c.req(`/api/matches/${s.id}/actions`,body);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(b.data.idempotent,true);assert.equal(a.data.snapshot.boards.human.revision,b.data.snapshot.boards.human.revision);});
test('forged opponent actor is rejected rather than selecting its board',async()=>{const c=await client(),s=await started(c);assert.equal((await c.req(`/api/matches/${s.id}/actions`,{requestId:crypto.randomUUID(),actor:'jev',action:{type:'resign'}})).status,422);});
test('resignation is verified and exposes sealed analytics with no fabricated clear time',async()=>{const c=await client(),s=await started(c);const end=await c.req(`/api/matches/${s.id}/actions`,{requestId:crypto.randomUUID(),action:{type:'resign'}});assert.equal(end.data.snapshot.outcome,'loss');assert.equal(end.data.snapshot.eligibility.verification,'verified');const r=await c.req(`/api/matches/${s.id}/analytics`);assert.equal(r.status,200);assert.equal(r.data.result.humanClearMs,null);assert.equal(r.data.players.human.actions,0);assert.equal((await c.req(`/api/matches/${s.id}/replay`)).data.seeds.human.length,64);});
test('a real generated board can be cleared and verified through the HTTP API',async()=>{const c=await client();let s=await started(c);for(let cell=0;cell<81;cell++){if(s.boards.human.status!=='active')break;const privateState=JSON.parse(app.store.match(s.id).private_state_json);if(privateState.boards.human.mines[cell]||s.boards.human.cells[cell]!==-1)continue;const r=await c.req(`/api/matches/${s.id}/actions`,{requestId:crypto.randomUUID(),expectedBoardRevision:s.boards.human.revision,action:{type:'reveal',cell}});assert.equal(r.status,200);s=r.data.snapshot;}await new Promise(r=>setTimeout(r,120));await app.manager.tick(s.id);s=(await c.req(`/api/matches/${s.id}`)).data;assert.equal(s.outcome,'win');assert.equal(s.eligibility.verification,'verified');const report=(await c.req(`/api/matches/${s.id}/analytics`)).data;assert.equal(report.players.human.revealedSafe,71);assert.ok(report.players.human.clearMs>=0);});
test('world leaderboard is public and channel scope needs a valid launch grant',async()=>{assert.equal((await fetch(base+'/api/leaderboard')).status,200);const c=await client();assert.equal((await c.req('/api/leaderboard?scope=channel')).status,403);});
test('admin analytics are unavailable without administrator authorization',async()=>assert.equal((await fetch(base+'/api/admin/analytics')).status,403));
test('profile and CSV exports are owner-only',async()=>{const c=await client();assert.equal((await c.req('/api/exports/me.json')).status,200);assert.equal((await fetch(base+'/api/exports/me.json')).status,401);assert.equal((await fetch(base+'/api/exports/history.csv',{headers:{cookie:c.cookie}})).status,200);});
test('Monday UTC boundary is explicit',()=>assert.equal(new Date(weekStart(Date.parse('2026-09-22T12:00:00Z'))).toISOString(),'2026-09-21T00:00:00.000Z'));
test('leaderboard qualifies at 20 matches and keeps channel populations isolated',()=>{const db=new Store(':memory:');try{const key=competitionKey(gameConfig(app.config,'beginner','normal'));for(const[id,name,games,winCount,channel]of[['111111111111111111','Alice',20,20,'channel-a'],['222222222222222222','Bob',20,10,'channel-b'],['333333333333333333','Charlie',19,19,'channel-a']]){db.run('INSERT INTO users(discord_id,display_name,created_at,last_seen_at) VALUES(?,?,0,0)',id,name);for(let i=0;i<games;i++)db.run("INSERT INTO matches(id,owner_key,creation_request_id,creation_body_hash,user_id,competition_key,board_preset,ai_difficulty,guild_id,channel_id,config_json,private_state_json,phase,eligible,verification,outcome,human_clear_ms,created_at,finished_at) VALUES(?,?,?,?,?,?,'beginner','normal','guild',?,'{}','{}','complete',1,'verified',?,1000,0,?)",`${id}-${i}`,`u:${id}`,`req-${i}`,'hash',id,key,channel,i<winCount?'win':'loss',i+1);}
 const world=leaderboard(db,app.config,null,new URLSearchParams());assert.equal(world.entries[0].displayName,'Alice');assert.equal(world.entries[0].rank,1);assert.equal(world.entries[2].displayName,'Charlie');assert.equal(world.entries[2].rank,null);
 const channel=leaderboard(db,app.config,{user_id:'111111111111111111',data:{context:{guildId:'guild',channelId:'channel-a',expiresAt:Date.now()+10000}}},new URLSearchParams({scope:'channel'}));assert.equal(channel.entries.length,2);assert.ok(!channel.entries.some(e=>e.displayName==='Bob'));
 }finally{db.close();}});
test('native HTTP SSE delivers an owner-filtered public snapshot',async()=>{
 const c=await client(),s=await started(c),controller=new AbortController();
 const response=await fetch(`${base}/api/matches/${s.id}/events`,{headers:{cookie:c.cookie},signal:controller.signal});
 assert.equal(response.status,200);assert.ok(response.headers.get('content-type').startsWith('text/event-stream'));
 const reader=response.body.getReader();let text='';
 try{while(!text.includes('\n\n')){const r=await reader.read();if(r.done)break;text+=new TextDecoder().decode(r.value);}const line=text.split('\n').find(x=>x.startsWith('data:'));assert.ok(line);const snapshot=JSON.parse(line.slice(5));assert.equal(snapshot.id,s.id);assert.equal(snapshot.boards.human.mines,undefined);assert.equal(snapshot.seeds,undefined);}finally{controller.abort();await reader.cancel().catch(()=>{});}
});
test('native HTTP SSE rejects another match owner',async()=>{const a=await client(),b=await client(),s=await started(a);assert.equal((await fetch(`${base}/api/matches/${s.id}/events`,{headers:{cookie:b.cookie}})).status,404);});
