import test,{before,after}from'node:test';import assert from'node:assert/strict';
import {createApp,leaderboard,weekStart}from'../server/main.js';import {loadConfig,gameConfig,competitionKey}from'../server/config.js';import {Store}from'../server/db.js';import {localDatabase}from'../server/local-db.js';import {HIGH,options,act,pagedReplay}from'./helpers.js';
import {analyzeReplay}from'../public/shared/analytics.js';import {verifyReplay}from'../public/shared/replay.js';
let app,base;
before(async()=>{app=await createApp({env:{PORT:'0',...HIGH}});base=await app.listen();});
after(async()=>await app.close());
async function client(){const r=await fetch(base+'/api/me'),cookie=r.headers.get('set-cookie').split(';')[0],me=await r.json();return{cookie,me,async req(path,body,extra={}){const response=await fetch(base+path,{method:body?'POST':'GET',headers:{cookie,origin:base,'content-type':'application/json','x-csrf-token':me.csrfToken,...extra},body:body?JSON.stringify(body):undefined});let data;try{data=await response.json();}catch{data=null;}return{status:response.status,data};}};}
async function started(c){const {data:s}=await c.req('/api/matches',options());const r=await c.req(`/api/matches/${s.id}/actions`,act({type:'start',cell:40}));assert.equal(r.status,200);return r.data.snapshot;}
const privateState=id=>JSON.parse(app.database.raw.prepare('SELECT private_state_json FROM matches WHERE id=?').get(id).private_state_json);
test('health endpoint returns success',async()=>assert.equal((await fetch(base+'/api/health')).status,200));
test('static root and CSP are served without framework code',async()=>{const r=await fetch(base);assert.equal(r.status,200);assert.ok(r.headers.get('content-security-policy').includes("frame-ancestors 'none'"));assert.ok((await r.text()).includes('humanBoard'));});
test('shared rules are served to the browser from public/shared',async()=>{for(const name of['engine','solver','decisions','replay','analytics'])assert.equal((await fetch(`${base}/shared/${name}.js`)).status,200);});
test('server files, migrations and environment files are not served',async()=>{for(const path of['/.env','/server/main.js','/server/worker.js','/migrations/0001_init.sql','/data/minesweeper.sqlite','/_headers','/%2e%2e/server/main.js'])assert.equal((await fetch(base+path)).status,404,path);});
test('guest match creation succeeds and cannot be ranked',async()=>{const c=await client(),r=await c.req('/api/matches',{...options(),mode:'ranked'});assert.equal(r.status,201);assert.equal(r.data.eligibility.eligible,false);assert.ok(r.data.eligibility.reasons.includes('guest'));});
test('browser-supplied guild and score fields are rejected',async()=>{const c=await client();for(const extra of[{guild_id:'fake'},{score:999999}])assert.equal((await c.req('/api/matches',{...options(),...extra})).status,422);});
test('match creation requires CSRF token',async()=>{const c=await client();assert.equal((await c.req('/api/matches',options(),{'x-csrf-token':'wrong'})).status,403);});
test('match creation requires same origin',async()=>{const c=await client();assert.equal((await c.req('/api/matches',options(),{origin:'https://attacker.invalid'})).status,403);});
test('duplicate creation id returns original match',async()=>{const c=await client(),body=options(),a=await c.req('/api/matches',body),b=await c.req('/api/matches',body);assert.equal(a.data.id,b.data.id);});
test('creation id cannot be reused with a different body',async()=>{const c=await client(),body=options();await c.req('/api/matches',body);assert.equal((await c.req('/api/matches',{...body,aiDifficulty:'hard'})).status,409);});
test('one owner cannot keep multiple active matches',async()=>{const c=await client();await c.req('/api/matches',options());assert.equal((await c.req('/api/matches',options())).status,409);});
test('different owner cannot read or act on a match',async()=>{const a=await client(),b=await client(),s=await started(a);assert.equal((await b.req(`/api/matches/${s.id}`)).status,404);assert.equal((await b.req(`/api/matches/${s.id}/actions`,act({type:'resign'}))).status,404);});
test('unknown UUID error does not crash audit logging',async()=>{const c=await client();assert.equal((await c.req(`/api/matches/${crypto.randomUUID()}/actions`,act({type:'resign'}))).status,404);assert.equal((await fetch(base+'/api/health')).status,200);});
test('active snapshots expose no hidden layout or seed',async()=>{const c=await client(),s=await started(c);assert.equal(s.seeds,undefined);assert.equal(s.boards.human.mines,undefined);assert.equal(s.boards.jev.adjacent,undefined);assert.equal(s.boards.human.cells.length,81);const polled=(await c.req(`/api/matches/${s.id}`)).data;assert.equal(JSON.stringify(polled).includes(privateState(s.id).seeds.human),false);});
test('active replay, journal export and post-game endpoints are locked',async()=>{const c=await client(),s=await started(c);for(const suffix of['replay','operations','export?format=jsonl'])assert.equal((await c.req(`/api/matches/${s.id}/${suffix}`)).status,409,suffix);});
test('the removed event-stream and server-analytics routes are gone',async()=>{const c=await client(),s=await started(c);assert.equal((await c.req(`/api/matches/${s.id}/events`)).status,404);assert.equal((await c.req(`/api/matches/${s.id}/analytics`)).status,404);assert.equal((await c.req(`/api/matches/${s.id}/export?format=csv`)).status,422);});
test('wrong human board revision is rejected',async()=>{const c=await client(),s=await started(c),cell=s.boards.human.cells.indexOf(-1);const r=await c.req(`/api/matches/${s.id}/actions`,act({type:'setFlag',cell,value:true},{expectedBoardRevision:0}));assert.equal(r.status,409);assert.equal(r.data.error.code,'stale_board_revision');});
test('idempotent action is applied exactly once',async()=>{const c=await client(),s=await started(c),cell=s.boards.human.cells.indexOf(-1);const body=act({type:'setFlag',cell,value:true},{expectedBoardRevision:s.boards.human.revision});const a=await c.req(`/api/matches/${s.id}/actions`,body),b=await c.req(`/api/matches/${s.id}/actions`,body);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(b.data.idempotent,true);assert.equal(a.data.snapshot.boards.human.revision,b.data.snapshot.boards.human.revision);});
test('a reused request id with a different body conflicts',async()=>{const c=await client(),s=await started(c),cells=s.boards.human.cells.flatMap((v,i)=>v===-1?[i]:[]);const requestId=crypto.randomUUID();const a=await c.req(`/api/matches/${s.id}/actions`,{requestId,expectedBoardRevision:s.boards.human.revision,action:{type:'setFlag',cell:cells[0],value:true}});assert.equal(a.status,200);const b=await c.req(`/api/matches/${s.id}/actions`,{requestId,expectedBoardRevision:s.boards.human.revision,action:{type:'setFlag',cell:cells[1],value:true}});assert.equal(b.status,409);assert.equal(b.data.error.code,'idempotency_conflict');});
test('two simultaneous commands on one revision cannot both apply',async()=>{const c=await client(),s=await started(c),cells=s.boards.human.cells.flatMap((v,i)=>v===-1?[i]:[]);const post=cell=>c.req(`/api/matches/${s.id}/actions`,act({type:'setFlag',cell,value:true},{expectedBoardRevision:s.boards.human.revision}));const [a,b]=await Promise.all([post(cells[0]),post(cells[1])]);assert.deepEqual([a.status,b.status].sort(),[200,409]);const now=(await c.req(`/api/matches/${s.id}`)).data;assert.equal(now.boards.human.revision,s.boards.human.revision+1);});
test('forged opponent actor is rejected rather than selecting its board',async()=>{const c=await client(),s=await started(c);assert.equal((await c.req(`/api/matches/${s.id}/actions`,act({type:'resign'},{actor:'jev'}))).status,422);});
async function untilVerified(c,snap){for(let i=0;i<120&&snap.eligibility.verification==='pending';i++){await app.idle();snap=(await c.req(`/api/matches/${snap.id}`)).data;}return snap;}
test('resignation is verified; analytics derive from the verified replay with no fabricated clear time',async()=>{
 const c=await client(),s=await started(c);const end=await c.req(`/api/matches/${s.id}/actions`,act({type:'resign'}));assert.equal(end.data.snapshot.outcome,'loss');
 const snap=await untilVerified(c,end.data.snapshot);assert.equal(snap.eligibility.verification,'verified');
 const replay=(await pagedReplay(c.req,s.id)).data,ops=(await c.req(`/api/matches/${s.id}/operations`)).data;
 assert.equal(replay.seeds.human.length,64);assert.equal(replay.events.at(-1).hash,replay.headHash);
 const report=await analyzeReplay(replay,{audits:ops.audits,pricePerMillion:ops.pricePerMillion,verified:true});
 assert.equal(report.result.humanClearMs,null);assert.equal(report.players.human.actions,0);assert.ok(report.operations.auditEvents>0);
});
test('a real generated board can be cleared and verified through the HTTP API',async()=>{const c=await client();let s=await started(c);for(let cell=0;cell<81;cell++){if(s.boards.human.status!=='active')break;if(privateState(s.id).boards.human.mines[cell]||s.boards.human.cells[cell]!==-1)continue;const r=await c.req(`/api/matches/${s.id}/actions`,act({type:'reveal',cell},{expectedBoardRevision:s.boards.human.revision}));assert.equal(r.status,200);s=r.data.snapshot;}
 await new Promise(r=>setTimeout(r,160));s=(await c.req(`/api/matches/${s.id}`)).data;assert.equal(s.outcome,'win');
 s=await untilVerified(c,s);assert.equal(s.eligibility.verification,'verified');
 const replay=(await pagedReplay(c.req,s.id)).data,report=await analyzeReplay(replay,{verified:true});assert.equal(report.players.human.revealedSafe,71);assert.ok(report.players.human.clearMs>=0);});
test('the replay is served in pages that reassemble into the verifiable document, and the jsonl journal is the stored events',async()=>{
 const c=await client(),s=await started(c);for(let i=0;i<30;i++){const snap=(await c.req(`/api/matches/${s.id}`)).data,cell=snap.boards.human.cells.indexOf(-1);await c.req(`/api/matches/${s.id}/actions`,act({type:'setFlag',cell,value:true},{expectedBoardRevision:snap.boards.human.revision}));}
 await c.req(`/api/matches/${s.id}/actions`,act({type:'resign'}));await app.idle();
 const stored=app.database.raw.prepare('SELECT event_json FROM match_events WHERE match_id=? ORDER BY seq').all(s.id).map(x=>x.event_json);assert.ok(stored.length>24,'more than one page');
 const first=(await c.req(`/api/matches/${s.id}/replay`)).data;assert.equal(first.page.count,24);assert.equal(first.page.next,25);assert.equal(first.page.total,stored.length);
 const replay=(await pagedReplay(c.req,s.id)).data;assert.equal(replay.events.length,stored.length);assert.deepEqual(replay.events.map(e=>JSON.stringify(e)),stored);
 assert.equal((await c.req(`/api/matches/${s.id}/replay?from=0`)).status,422);
 let lines=[],from=1;while(from){const r=await fetch(`${base}/api/matches/${s.id}/export?format=jsonl&from=${from}`,{headers:{cookie:c.cookie}});assert.equal(r.status,200);lines.push(...(await r.text()).trim().split(String.fromCharCode(10)));from=Number(r.headers.get('x-next-seq'))||0;}
 assert.deepEqual(lines,stored);
 for(let i=0;i<80&&(await c.req(`/api/matches/${s.id}`)).data.eligibility.verification==='pending';i++)await app.idle();
 const verified=await verifyReplay(replay);assert.equal(verified.verified,true,'the reassembled document verifies offline with the shared verifier');
});
test('world leaderboard is public and channel scope needs a valid launch grant',async()=>{assert.equal((await fetch(base+'/api/leaderboard')).status,200);const c=await client();assert.equal((await c.req('/api/leaderboard?scope=channel')).status,403);});
test('admin analytics are unavailable without administrator authorization',async()=>assert.equal((await fetch(base+'/api/admin/analytics')).status,403));
test('profile and CSV exports are owner-only',async()=>{const c=await client();assert.equal((await c.req('/api/exports/me.json')).status,200);assert.equal((await fetch(base+'/api/exports/me.json')).status,401);assert.equal((await fetch(base+'/api/exports/history.csv',{headers:{cookie:c.cookie}})).status,200);});
test('Monday UTC boundary is explicit',()=>assert.equal(new Date(weekStart(Date.parse('2026-09-22T12:00:00Z'))).toISOString(),'2026-09-21T00:00:00.000Z'));
test('leaderboard qualifies at 20 matches and keeps channel populations isolated',async()=>{const db=localDatabase(),store=new Store(db);try{const config=loadConfig({DEV_LOCAL:'1'}),key=competitionKey(gameConfig(config,'beginner','normal'));for(const[id,name,games,winCount,channel]of[['111111111111111111','Alice',20,20,'channel-a'],['222222222222222222','Bob',20,10,'channel-b'],['333333333333333333','Charlie',19,19,'channel-a']]){db.raw.prepare('INSERT INTO users(discord_id,display_name,created_at,last_seen_at) VALUES(?,?,0,0)').run(id,name);for(let i=0;i<games;i++)db.raw.prepare("INSERT INTO matches(id,owner_key,creation_request_id,creation_body_hash,user_id,competition_key,board_preset,ai_difficulty,guild_id,channel_id,config_json,private_state_json,phase,eligible,verification,outcome,human_clear_ms,created_at,finished_at) VALUES(?,?,?,?,?,?,'beginner','normal','guild',?,'{}','{}','complete',1,'verified',?,1000,0,?)").run(`${id}-${i}`,`u:${id}`,`req-${i}`,'hash',id,key,channel,i<winCount?'win':'loss',i+1);}
 const world=await leaderboard(store,config,null,new URLSearchParams());assert.equal(world.entries[0].displayName,'Alice');assert.equal(world.entries[0].rank,1);assert.equal(world.entries[2].displayName,'Charlie');assert.equal(world.entries[2].rank,null);
 const channel=await leaderboard(store,config,{user_id:'111111111111111111',data:{context:{guildId:'guild',channelId:'channel-a',expiresAt:Date.now()+10000}}},new URLSearchParams({scope:'channel'}));assert.equal(channel.entries.length,2);assert.ok(!channel.entries.some(e=>e.displayName==='Bob'));
 }finally{db.close();}});
