import test from 'node:test';
import assert from 'node:assert/strict';
import {neighbors,generateBoard,boardFromMines,applyBoardAction,observeBoard,observeMatch,createMatch,startMatch,applyMatchAction,adjudicate,finish,validateConfig,canonical,clone} from '../shared/engine.js';
import {config,seeds,game} from './helpers.js';
for(const[cell,count]of[[0,3],[1,5],[4,8],[8,3]])test(`neighbors do not wrap at cell ${cell}`,()=>assert.equal(neighbors(cell,3,3).length,count));
test('invalid board configuration is rejected',()=>assert.throws(()=>validateConfig({width:3,height:3,mineCount:1}),/invalid_config/));
test('invalid difficulty rejected',()=>assert.throws(()=>validateConfig({...config,aiDifficulty:'impossible'}),/invalid_difficulty/));
test('same generator inputs reconstruct same board',async()=>assert.deepEqual(await generateBoard(config,seeds.human,40),await generateBoard(config,seeds.human,40)));
test('independent seeds yield distinct layouts',async()=>assert.notDeepEqual((await generateBoard(config,seeds.human,40)).mines,(await generateBoard(config,seeds.jev,40)).mines));
test('malformed seeds are rejected',async()=>await assert.rejects(generateBoard(config,'x',40),/invalid_seed/));
test('protected opening and mine count hold at every beginner coordinate',async()=>{for(let c=0;c<81;c++){const b=await generateBoard(config,seeds.human,c);assert.equal(b.mines.reduce((a,b)=>a+b),10);for(const i of[c,...neighbors(c,9,9)])assert.equal(b.mines[i],0);}});
test('generator is deterministic across a 30-seed sample',async()=>{for(let i=0;i<30;i++){const seed=i.toString(16).padStart(64,'0');const a=await generateBoard(config,seed,i),b=await generateBoard(config,seed,i);assert.deepEqual(a.mines,b.mines);}});
test('duplicate mine positions rejected',()=>assert.throws(()=>boardFromMines(3,3,[1,1]),/duplicate_mine/));
test('flag placement is not completion',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'setFlag',cell:0,value:true},10);assert.equal(b.status,'active');assert.equal(b.revealedSafe,0);});
test('flagged cells cannot be revealed',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'setFlag',cell:1,value:true},10);assert.throws(()=>applyBoardAction(b,{type:'reveal',cell:1},20),/illegal_reveal/);});
test('repeated explicit flag is rejected as no change',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'setFlag',cell:0,value:true},10);assert.throws(()=>applyBoardAction(b,{type:'setFlag',cell:0,value:true},20),/no_change/);});
test('unflag returns a covered cell',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'setFlag',cell:0,value:true},10);applyBoardAction(b,{type:'setFlag',cell:0,value:false},20);assert.equal(observeBoard(b).cells[0],-1);});
test('zero expansion clears all connected safe cells',()=>{const b=boardFromMines(3,3,[0]);const d=applyBoardAction(b,{type:'reveal',cell:8},10);assert.equal(d.safeDelta,8);assert.equal(b.status,'cleared');});
test('zero expansion respects a flag on a safe cell',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'setFlag',cell:8,value:true},10);applyBoardAction(b,{type:'reveal',cell:7},20);assert.equal(b.revealed[8],0);assert.equal(b.status,'active');});
test('correct chord can complete a board',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'reveal',cell:4},10);applyBoardAction(b,{type:'setFlag',cell:0,value:true},20);applyBoardAction(b,{type:'chord',cell:4},30);assert.equal(b.status,'cleared');});
test('unsafe chord explodes even while revealing other safe cells',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'reveal',cell:4},10);applyBoardAction(b,{type:'setFlag',cell:1,value:true},20);applyBoardAction(b,{type:'chord',cell:4},30);assert.equal(b.status,'exploded');assert.equal(b.explodedCell,0);});
test('chord requires matching flag count',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'reveal',cell:4},10);assert.throws(()=>applyBoardAction(b,{type:'chord',cell:4},20),/illegal_chord/);});
test('mine reveal is legal and terminal, not a validation rejection',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'reveal',cell:0},10);assert.equal(b.status,'exploded');});
test('terminal boards reject further actions',()=>{const b=boardFromMines(3,3,[0]);applyBoardAction(b,{type:'reveal',cell:0},10);assert.throws(()=>applyBoardAction(b,{type:'reveal',cell:1},20),/board_inactive/);});
test('out of range action is rejected before mutation',()=>{const b=boardFromMines(3,3,[0]);assert.throws(()=>applyBoardAction(b,{type:'reveal',cell:9},10),/invalid_cell/);assert.equal(b.revision,0);});
test('unknown action type is rejected',()=>assert.throws(()=>applyBoardAction(boardFromMines(3,3,[0]),{type:'teleport',cell:0},10),/invalid_action/));
test('first coordinate opens both independent boards',async()=>{const s=await game();assert.equal(s.boards.human.revealed[40],1);assert.equal(s.boards.jev.revealed[40],1);assert.notDeepEqual(s.boards.human.mines,s.boards.jev.mines);});
test('public match projection contains no seeds, bitmap, or hidden adjacency',async()=>{const s=await game();const v=observeMatch(s);const forbidden=['seeds','mines','adjacent','private_state_json'];function scan(x){if(!x||typeof x!=='object')return;for(const[k,value]of Object.entries(x)){assert.ok(!forbidden.includes(k),k);scan(value);}}scan(v);assert.equal(v.boards.human.cells.length,81);});
test('ready public projection does not contain seeds',async()=>{const s=await createMatch(config,seeds);assert.equal(observeMatch(s).boards.human.cells.filter(v=>v===-1).length,81);assert.equal('seeds'in observeMatch(s),false);});
test('one explosion does not award the surviving player a win',async()=>{const s=await game();s.boards.jev.status='exploded';s.boards.jev.terminalAtMs=20;assert.equal(adjudicate(s,1000),false);assert.equal(s.phase,'running');});
test('two exploded boards draw',async()=>{const s=await game();for(const b of Object.values(s.boards)){b.status='exploded';b.terminalAtMs=20;}assert.equal(adjudicate(s,30),true);assert.equal(s.outcome,'draw');});
test('clears in the same interval draw',async()=>{const s=await game();s.boards.human.status=s.boards.jev.status='cleared';s.boards.human.terminalAtMs=151;s.boards.jev.terminalAtMs=199;assert.equal(adjudicate(s,199),false);assert.equal(adjudicate(s,200),true);assert.equal(s.outcome,'draw');});
test('an earlier clear bucket wins',async()=>{const s=await game();s.boards.human.status=s.boards.jev.status='cleared';s.boards.human.terminalAtMs=199;s.boards.jev.terminalAtMs=201;adjudicate(s,300);assert.equal(s.outcome,'win');});
test('actions after an unresolved winning interval are rejected',async()=>{const s=await game();s.boards.jev.status='cleared';s.boards.jev.terminalAtMs=100;assert.throws(()=>applyMatchAction(s,'human',{type:'reveal',cell:0},200),/adjudication_due/);});
test('deadline without completion draws',async()=>{const s=await game();adjudicate(s,900000);assert.equal(s.outcomeReason,'deadline');});
test('actions at deadline are not accepted',async()=>{const s=await game();assert.throws(()=>applyMatchAction(s,'human',{type:'reveal',cell:0},900000),/deadline/);});
test('non-monotonic time is rejected',async()=>{const s=await game();s.lastAtMs=100;assert.throws(()=>adjudicate(s,99),/non_monotonic/);});
test('resignation is a human loss',async()=>{const s=await game();finish(s,'loss','resigned',500);assert.equal(s.outcome,'loss');});
test('canonical object key ordering is stable',()=>assert.equal(canonical({b:1,a:[2,3]}),canonical({a:[2,3],b:1})));
test('HMAC generator matches frozen cross-runtime vectors',async()=>{
 const {readFile}=await import('node:fs/promises');const fixture=JSON.parse(await readFile(new URL('./fixtures/generation.json',import.meta.url),'utf8'));
 for(const v of fixture.vectors){const b=await generateBoard(v,v.seed,v.firstCell);assert.deepEqual(b.mines.flatMap((m,i)=>m?[i]:[]),v.mineCells);}
});
