import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign} from 'node:crypto';
import {Store} from '../server/db.js';import {loadConfig} from '../server/config.js';
import {token,hash,equal,createSession,getSession,csrf,verifyDiscordSignature,RateLimiter,ownerKey} from '../server/security.js';
import {loginUrl,oauthCallback,interaction,resolveContext,authorizeScope} from '../server/discord.js';
const config={...loadConfig({PORT:'0',APP_ORIGIN:'http://localhost:3000'}),discordClientId:'111111111111111111',discordClientSecret:'test-client-secret'};
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;}});
const userA='222222222222222222',userB='333333333333333333';
function fixture(){const store=new Store(':memory:');store.run('INSERT INTO users(discord_id,display_name,created_at,last_seen_at) VALUES(?,?,?,?)',userA,'Alice',0,0);store.run('INSERT INTO users(discord_id,display_name,created_at,last_seen_at) VALUES(?,?,?,?)',userB,'Bob',0,0);return store;}
test('constant-time token comparison preserves equality semantics',()=>{assert.ok(equal('abc','abc'));assert.ok(!equal('abc','abcd'));assert.ok(!equal(null,'x'));});
test('secure tokens are 256-bit opaque strings',()=>{const a=token(),b=token();assert.equal(a.length,43);assert.notEqual(a,b);assert.equal(hash(a).length,64);});
test('session tokens are stored hashed, not raw',()=>{const db=fixture();try{const {raw,session}=createSession(db,config);assert.notEqual(raw,session.token_hash);assert.equal(db.get('SELECT token_hash FROM sessions').token_hash,hash(raw));}finally{db.close();}});
test('expired session is not accepted',()=>{const db=fixture();try{const {raw}=createSession(db,config,null,{},0);assert.equal(getSession({headers:{cookie:`jev_session=${raw}`}},response(),db,config,{now:config.sessionAbsoluteMs+1}),null);}finally{db.close();}});
test('idle sessions expire before their absolute lifetime',()=>{const db=fixture();try{const {raw}=createSession(db,config,null,{},0);assert.equal(getSession({headers:{cookie:`jev_session=${raw}`}},response(),db,config,{now:config.sessionIdleMs+1}),null);}finally{db.close();}});
test('CSRF requires both a matching origin and matching synchronizer token',()=>{const s={csrf_token:'same'};assert.doesNotThrow(()=>csrf({headers:{origin:config.origin,'x-csrf-token':'same'}},s,config));assert.throws(()=>csrf({headers:{origin:'https://attacker.invalid','x-csrf-token':'same'}},s,config));assert.throws(()=>csrf({headers:{origin:config.origin,'x-csrf-token':'wrong'}},s,config));});
test('OAuth requests only identify scope and stores one-time state hash',()=>{const db=fixture();try{const {session}=createSession(db,config);const url=new URL(loginUrl(db,config,session));assert.equal(url.searchParams.get('scope'),'identify');assert.equal(session.data.oauth.stateHash,hash(url.searchParams.get('state')));assert.equal(url.searchParams.get('redirect_uri'),config.origin+'/api/auth/discord/callback');}finally{db.close();}});
test('OAuth state mismatch is rejected before token exchange',async()=>{const db=fixture();try{const {session}=createSession(db,config);loginUrl(db,config,session);await assert.rejects(oauthCallback({store:db,config,session,params:new URLSearchParams({state:'wrong',code:'x'}),res:response(),fetchImpl:()=>{throw Error('must not fetch');}}),/state rejected/);}finally{db.close();}});
test('OAuth callback rotates session and persists no OAuth tokens',async()=>{const db=fixture();try{const {session}=createSession(db,config);const url=new URL(loginUrl(db,config,session));let calls=0;const fresh=await oauthCallback({store:db,config,session,params:new URLSearchParams({state:url.searchParams.get('state'),code:'example-code'}),res:response(),fetchImpl:async()=>new Response(JSON.stringify(++calls===1?{access_token:'ephemeral-access',refresh_token:'ephemeral-refresh'}:{id:userA,username:'Alice',avatar:null}),{status:200})});assert.equal(fresh.user_id,userA);assert.notEqual(fresh.token_hash,session.token_hash);assert.equal(db.get('SELECT * FROM sessions WHERE token_hash=?',session.token_hash),undefined);assert.ok(!JSON.stringify(db.all('SELECT * FROM sessions')).includes('ephemeral-access'));}finally{db.close();}});
const pair=generateKeyPairSync('ed25519'),publicHex=pair.publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('hex');
function signed(payload,now=Date.now()){const raw=Buffer.from(JSON.stringify(payload)),timestamp=String(Math.floor(now/1000));return{raw,headers:{'x-signature-timestamp':timestamp,'x-signature-ed25519':sign(null,Buffer.concat([Buffer.from(timestamp),raw]),pair.privateKey).toString('hex')}};}
test('Discord signatures validate only the exact timestamp and raw body',()=>{const a=signed({type:1});assert.ok(verifyDiscordSignature(a.raw,a.headers,publicHex));assert.ok(!verifyDiscordSignature(Buffer.from('{}'),a.headers,publicHex));});
test('stale Discord signature is rejected',()=>{const a=signed({type:1},Date.now()-400000);assert.ok(!verifyDiscordSignature(a.raw,a.headers,publicHex));});
test('Discord signed ping returns type one',()=>{const db=fixture();try{assert.deepEqual(interaction({...signed({type:1}),store:db,config:{...config,discordPublicKey:publicHex}}),{type:1});}finally{db.close();}});
test('guild interaction creates user-bound one-time launch ticket',()=>{const db=fixture();try{const payload={id:'444444444444444444',application_id:config.discordClientId,type:2,guild_id:'555555555555555555',channel_id:'666666666666666666',channel:{type:0},member:{user:{id:userA}},data:{name:'jev',options:[{name:'play',type:1}]}};const reply=interaction({...signed(payload),store:db,config:{...config,discordPublicKey:publicHex}});const launch=new URL(reply.data.components[0].components[0].url).hash.split('=')[1];const a=createSession(db,config,userA).session,b=createSession(db,config,userB).session;assert.equal(resolveContext(db,a,{launchTicket:launch},config).guildId,payload.guild_id);assert.throws(()=>resolveContext(db,b,{launchTicket:launch},config),/ticket rejected/);const t=db.get('SELECT * FROM launch_tickets');assert.equal(t.token_hash,hash(launch));assert.ok(!JSON.stringify(t).includes(launch));}finally{db.close();}});
test('forged community scope cannot be authorized by query parameters',()=>{assert.throws(()=>authorizeScope({user_id:userA,data:{}},'channel'),/community launch/);assert.equal(authorizeScope(null,'world'),null);});
test('expired launch-context grant is rejected',()=>assert.throws(()=>authorizeScope({user_id:userA,data:{context:{guildId:'x',expiresAt:0}}},'server'),/community launch/));
test('bounded limiter respects a fixed window',()=>{const l=new RateLimiter();assert.ok(l.take('x',2,1000,0));assert.ok(l.take('x',2,1000,1));assert.ok(!l.take('x',2,1000,2));assert.ok(l.take('x',2,1000,1000));});
test('transaction rollback is atomic',()=>{const db=fixture();try{assert.throws(()=>db.transaction(()=>{db.run("UPDATE users SET display_name='Changed'");throw Error('rollback');}));assert.equal(db.get('SELECT display_name FROM users WHERE discord_id=?',userA).display_name,'Alice');}finally{db.close();}});
